### ISSUE TITLE
The purpose of Pulsar 

### ISSUE THREAD

**Issue by HelloTo4x** [psisoyev/train-station#197]
Hi, i am reading your project, why don't u use Kafka or RabbitMQ as message queue instead of Pulsar, can you tell me why you choose Pulsar, do you know the pros and cons of Pulsar, if yes, can tell me, thank u so much

**Comment by psisoyev** [comment]
Hi,

That is a very good question. However, comparing message broker systems wasn't part of the blog post. You can find a couple of comparison blog posts on the Internet. Take into account that those blog posts might be opinionated and might not cover your use case. 

In my blog post, I've chosen Apache Pulsar for several reasons: there are plenty of blog posts about Apache Kafka and not that much about Apache Pulsar. Pulsar is a great message broker who has taken some weak sides of Kafka and improved them on the architectural level. For example, stateless brokers remove the need for rebalancing, making the system more flexible in resource consumption. Also, from a developer perspective, you don't need to bother yourself with offset management. I think Apache Pulsar is a more straightforward tool with some advantages. We are using it in a production environment in my current work, and I'm maintaining [neutron](https://github.com/cr-org/neutron) - a functional Scala wrapper around the Pulsar Java library. 

Let me know if you have more questions. Cheers!

**Comment by HelloTo4x** [comment]
sure, thank u
